#!/bin/bash

echo "Setting up environment variables..."
echo ""
echo "IMPORTANT: Please set your actual API keys as environment variables:"
echo ""
echo "For Gemini API:"
echo "export GEMINI_API_KEY=\"your_gemini_api_key_here\""
echo ""
echo "Add these exports to your ~/.bashrc, ~/.bash_profile, or ~/.zshrc file"
echo "Then restart your terminal and Claude Desktop for changes to take effect."
echo ""
echo "To verify variables are set, run:"
echo "echo \$GEMINI_API_KEY"
echo ""